# Data Manipulation Studio

For this studio, we will revisit our California farmers looking for advice on growing pumpkins and the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [12]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import numpy as np

Baltimore = pd.read_csv("dataset/baltimore_9-24-2016_9-30-2017.csv")
Boston = pd.read_csv("dataset/boston_9-24-2016_9-30-2017.csv")
NewYork = pd.read_csv("dataset/new-york_9-24-2016_9-30-2017.csv")
Philly = pd.read_csv("dataset/philadelphia_9-24-2016_9-30-2017.csv")

## Clean Your Data

In the last lesson, we cleaned the data to related to San Francisco. Pull up your notebook from the last lesson and use your cleaning skills to clean the dataframes as necessary.

In [21]:
# Clean your data here!
Baltimore.head()

Baltimore.clean = Baltimore.drop(["Grade", "Crop", "Storage", "Appearance", "Condition", "Quality", "Unit of Sale", "Environment", "Origin District", "Sub Variety", "Commodity Name", "Mostly Low", "Mostly High", "Trans Mode"], axis=1)

,City Name,Type,Package,Variety,Grade,Date,Low Price,High Price,Origin,Item Size,Color,Repack
0,BALTIMORE,NaN,24 inch bins,NaN,NaN,04/29/2017,270,280.0,NaN,lge,NaN,E
1,BALTIMORE,NaN,24 inch bins,NaN,NaN,05/06/2017,270,280.0,NaN,lge,NaN,E
2,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,DELAWARE,med,NaN,N
3,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,VIRGINIA,med,NaN,N
4,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,11/05/2016,90,100.0,MARYLAND,lge,NaN,N

In [45]:
Balti = Baltimore.clean.drop_duplicates()
Balti

,City Name,Type,Package,Variety,Grade,Date,Low Price,High Price,Origin,Item Size,Color,Repack
0,BALTIMORE,NaN,24 inch bins,NaN,NaN,04/29/2017,270,280.0,NaN,lge,NaN,E
1,BALTIMORE,NaN,24 inch bins,NaN,NaN,05/06/2017,270,280.0,NaN,lge,NaN,E
2,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,DELAWARE,med,NaN,N
3,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,VIRGINIA,med,NaN,N
4,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,11/05/2016,90,100.0,MARYLAND,lge,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...
148,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,09/30/2017,18,18.0,MARYLAND,NaN,ORANGE,N
149,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,09/30/2017,18,18.0,PENNSYLVANIA,NaN,ORANGE,N
150,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,09/24/2016,15,15.0,MARYLAND,sml,NaN,N
151,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,10/01/2016,15,15.0,MARYLAND,sml,NaN,N
152,BALTIMORE,NaN,1/2 bushel cartons,MINIATURE,NaN,10/08/2016,15,15.0,MARYLAND,sml,NaN,N

In [27]:
NewYork_clean = NewYork.drop(["Grade", "Crop", "Storage", "Appearance", "Condition", "Quality", "Unit of Sale", "Environment", "Origin District", "Sub Variety", "Commodity Name", "Mostly Low", "Mostly High", "Trans Mode"], axis=1)

NY= NewYork_clean.drop_duplicates()
NY

,City Name,Type,Package,Variety,Date,Low Price,High Price,Origin,Item Size,Color,Repack
0,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,150,170,MICHIGAN,xlge,NaN,N
1,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,150,170,MICHIGAN,lge,NaN,N
2,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,130,150,NEW JERSEY,xlge,NaN,N
3,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,130,150,NEW JERSEY,lge,NaN,N
4,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,120,140,NEW YORK,med-lge,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...
105,NEW YORK,NaN,1/2 bushel cartons,MINIATURE,09/23/2017,16,18,OHIO,sml,NaN,N
106,NEW YORK,NaN,1/2 bushel cartons,MINIATURE,09/30/2017,16,18,OHIO,sml,NaN,N
107,NEW YORK,NaN,bushel cartons,MINIATURE,09/09/2017,32,32,OHIO,sml,NaN,N
110,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,10/15/2016,18,18,NEW YORK,med,NaN,N
111,NEW YORK,NaN,1 1/9 bushel crates,MINIATURE,10/15/2016,18,18,NEW YORK,sml,NaN,N

In [31]:
Boston_clean = Boston.drop(["Grade", "Crop", "Storage", "Appearance", "Condition", "Quality", "Unit of Sale", "Environment", "Origin District", "Sub Variety", "Commodity Name", "Mostly Low", "Mostly High", "Trans Mode"], axis=1)
Boston_clean= Boston_clean.drop_duplicates()
Boston_clean

,City Name,Type,Package,Variety,Date,Low Price,High Price,Origin,Item Size,Color,Repack
0,BOSTON,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,CANADA,exjbo,ORANGE,N
1,BOSTON,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,CANADA,jbo,ORANGE,N
2,BOSTON,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,160,200,CANADA,xlge,ORANGE,N
4,BOSTON,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,160,180,CANADA,lge,ORANGE,N
6,BOSTON,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,140,160,CANADA,med-lge,ORANGE,N
...,...,...,...,...,...,...,...,...,...,...,...
333,BOSTON,NaN,1/2 bushel cartons,MINIATURE,10/22/2016,15,18,MASSACHUSETTS,sml,ORANGE,N
334,BOSTON,NaN,1/2 bushel cartons,MINIATURE,10/29/2016,15,18,MASSACHUSETTS,sml,WHITE,N
335,BOSTON,NaN,1/2 bushel cartons,MINIATURE,10/29/2016,15,18,MASSACHUSETTS,sml,ORANGE,N
336,BOSTON,NaN,1/2 bushel cartons,MINIATURE,11/05/2016,15,18,MASSACHUSETTS,sml,ORANGE,N
337,BOSTON,NaN,1/2 bushel cartons,MINIATURE,11/05/2016,15,18,MASSACHUSETTS,sml,WHITE,N

In [33]:
Philly_clean = Philly.drop(["Grade", "Crop", "Storage", "Appearance", "Condition", "Quality", "Unit of Sale", "Environment", "Origin District", "Sub Variety", "Commodity Name", "Mostly Low", "Mostly High", "Trans Mode"], axis=1)
Philly_clean = Philly_clean.drop_duplicates()
Philly_clean

,City Name,Type,Package,Variety,Date,Low Price,High Price,Origin,Item Size,Color,Repack
0,PHILADELPHIA,NaN,24 inch bins,HOWDEN TYPE,09/16/2017,140,150,PENNSYLVANIA,lge,NaN,N
1,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,150,150,NEW YORK,med-lge,NaN,N
2,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,150,150,NEW YORK,med,NaN,N
3,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/24/2016,150,160,PENNSYLVANIA,lge,NaN,N
4,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/01/2016,140,140,NEW JERSEY,med-lge,NaN,N
5,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/01/2016,140,140,PENNSYLVANIA,med-lge,NaN,N
6,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/01/2016,120,120,PENNSYLVANIA,med,NaN,N
7,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/08/2016,140,155,NEW JERSEY,med,NaN,N
8,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/08/2016,120,120,NEW JERSEY,sml,NaN,N
9,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/15/2016,120,125,PENNSYLVANIA,lge,NaN,N
10,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/15/2016,100,125,PENNSYLVANIA,med,NaN,N
11,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/22/2016,130,140,NEW JERSEY,med-lge,NaN,N
12,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/22/2016,120,120,PENNSYLVANIA,lge,NaN,N
13,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/22/2016,130,140,PENNSYLVANIA,med-lge,NaN,N
14,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/22/2016,100,120,PENNSYLVANIA,med,NaN,N
15,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/29/2016,130,140,NEW JERSEY,med-lge,NaN,N
16,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/29/2016,120,120,PENNSYLVANIA,lge,NaN,N
17,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/29/2016,130,140,PENNSYLVANIA,med-lge,NaN,N
18,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,10/29/2016,100,120,PENNSYLVANIA,med,NaN,N
19,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/16/2017,120,120,PENNSYLVANIA,lge,NaN,N
20,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/16/2017,120,150,PENNSYLVANIA,med,NaN,N
21,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/23/2017,140,140,DELAWARE,lge,NaN,N
22,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/23/2017,150,150,DELAWARE,med,NaN,N
23,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/23/2017,120,150,NEW YORK,lge,NaN,N
24,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/23/2017,140,150,PENNSYLVANIA,xlge,NaN,N
25,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/23/2017,140,150,PENNSYLVANIA,lge,NaN,N
26,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/30/2017,140,140,DELAWARE,lge,NaN,N
27,PHILADELPHIA,NaN,36 inch bins,HOWDEN TYPE,09/30/2017,140,140,DELAWARE,med,NaN,N
28,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,10/15/2016,12,14,OHIO,med,NaN,N
29,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,10/22/2016,12,12,OHIO,med,NaN,N
30,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,10/29/2016,12,12,OHIO,med,NaN,N
31,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,08/26/2017,18,20,MICHIGAN,med,NaN,N
32,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,09/16/2017,18,18,OHIO,med,NaN,N
33,PHILADELPHIA,NaN,1 1/9 bushel cartons,PIE TYPE,09/23/2017,18,22,OHIO,med,NaN,N
34,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,10/01/2016,250,250,PENNSYLVANIA,med,NaN,N
35,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,10/15/2016,140,140,PENNSYLVANIA,med,NaN,N
36,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,10/22/2016,140,150,PENNSYLVANIA,med,NaN,N
37,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,10/22/2016,75,100,PENNSYLVANIA,sml,NaN,N
38,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,10/29/2016,140,150,PENNSYLVANIA,med,NaN,N
39,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,10/29/2016,75,100,PENNSYLVANIA,sml,NaN,N
40,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,09/23/2017,180,180,DELAWARE,med,NaN,N
41,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,09/23/2017,140,140,DELAWARE,sml,NaN,N
42,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,09/23/2017,180,180,NEW YORK,med,NaN,N
43,PHILADELPHIA,NaN,24 inch bins,PIE TYPE,09/30/2017,140,140,DELAWARE,sml,NaN,N
44,PHILADELPHIA,NaN,24 inch bins,KNUCKLE HEAD,10/08/2016,210,210,NEW JERSEY,med,NaN,N
45,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,09/24/2016,17,18,OHIO,NaN,NaN,N
46,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,10/01/2016,18,18,NEW JERSEY,NaN,NaN,N
47,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,10/01/2016,17,18,OHIO,NaN,NaN,N
48,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,10/08/2016,15,15,OHIO,NaN,NaN,N
49,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,10/15/2016,15,18,OHIO,NaN,NaN,N
50,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,10/22/2016,16,18,OHIO,NaN,NaN,N
51,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,10/29/2016,16,18,OHIO,NaN,NaN,N
52,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,11/05/2016,16,18,OHIO,NaN,NaN,N
53,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,08/26/2017,18,20,MICHIGAN,NaN,NaN,N
54,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,09/16/2017,16,16,OHIO,NaN,NaN,N
55,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,09/23/2017,15,16,OHIO,NaN,NaN,N
56,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,09/30/2017,15,18,OHIO,NaN,NaN,N

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [39]:
# Combine the four dataframes into one!
Northeast = pd.concat([Balti, NY, Boston_clean, Philly_clean])
Northeast

,City Name,Type,Package,Variety,Grade,Date,Low Price,High Price,Origin,Item Size,Color,Repack
0,BALTIMORE,NaN,24 inch bins,NaN,NaN,04/29/2017,270,280.0,NaN,lge,NaN,E
1,BALTIMORE,NaN,24 inch bins,NaN,NaN,05/06/2017,270,280.0,NaN,lge,NaN,E
2,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,DELAWARE,med,NaN,N
3,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,160,160.0,VIRGINIA,med,NaN,N
4,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,11/05/2016,90,100.0,MARYLAND,lge,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...
52,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,NaN,11/05/2016,16,18.0,OHIO,NaN,NaN,N
53,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,NaN,08/26/2017,18,20.0,MICHIGAN,NaN,NaN,N
54,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,NaN,09/16/2017,16,16.0,OHIO,NaN,NaN,N
55,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,NaN,09/23/2017,15,16.0,OHIO,NaN,NaN,N
56,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,NaN,09/30/2017,15,18.0,OHIO,NaN,NaN,N

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of unit of sale in the Northeast region? In the last lesson, we learned that a unit of sale could be something like a bin or individually. 
2. What is the average number of pumpkins for each variety that came into terminal markets for the year by region? Pumpkin varieties include Howden and Fairytale pumpkins.

In [69]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
Northeast.agg('mean')

Type                 NaN
Grade                NaN
Low Price     136.790769
High Price    153.453077
dtype: float64

In [70]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
Market_avg = Northeast.groupby("City Name")
Market_avg

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!